project:
  type: website
  output-dir: docs

website:
  title: "Sahand Yazdani"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - projects.qmd
      - publications.qmd
      - about.qmd
      

format:
  html:
    theme: sandstone
    css: styles.css
    toc: true
    mainfont: arial
    fontsize: 1rem
    monofont: courier new
    
  
sass:
  sass_dir: assets/css
    
editor: visual
